name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish-js:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        working-directory: ./Languages/JavaScript
        run: npm install

      - name: Run tests
        working-directory: ./Languages/JavaScript
        run: npm test

      - name: Publish JavaScript Package
        working-directory: ./Languages/JavaScript
        run: npm publish --access public --provenance

  publish-ts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        working-directory: ./Languages/TypeScript
        run: npm ci

      - name: Build
        working-directory: ./Languages/TypeScript
        run: npm run build

      - name: Run tests
        working-directory: ./Languages/TypeScript
        run: npm test

      - name: Publish TypeScript Package
        working-directory: ./Languages/TypeScript
        run: npm publish --access public --provenance